### ISSUE TITLE
Waveformview dies after pressing m  twice for mean waveforms 

### ISSUE THREAD

**Issue by shabnamkadir** [kwikteam/phy#603]
My latest catastrope. This time I only had a clustering wtih 680 spikes.
```
gui50 = session50.show_gui()


20:04:11 [I] Split 37 spikes.
20:04:28 [I] Undo assign.
20:04:36 [I] Split 51 spikes.
20:04:42 [I] Undo assign.
20:08:41 [I] Split 36 spikes.
20:09:16 [I] Undo assign.

WARNING: Traceback (most recent call last):
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/IPython/kernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/IPython/kernel/zmq/kernelapp.py", line 373, in start
    ioloop.IOLoop.instance().start()
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/tornado/ioloop.py", line 810, in start
    self._run_callback(callback)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/IPython/kernel/zmq/kernelbase.py", line 234, in enter_eventloop
    self.eventloop(self)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/IPython/kernel/zmq/eventloops.py", line 80, in loop_qt4
    start_event_loop_qt4(kernel.app)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/IPython/lib/guisupport.py", line 135, in start_event_loop_qt4
    app.exec_()
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/vispy/app/backends/_qt.py", line 631, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/vispy/util/event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/vispy/util/event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/vispy/util/event.py", line 448, in _invoke_callback
    cb(event)
  File "/home/skadir/globalphy/phy/phy/plot/waveforms.py", line 484, in on_draw
    self.visual.draw()
  File "/home/skadir/globalphy/phy/phy/plot/_vispy_utils.py", line 144, in draw
    self._bake()
  File "/home/skadir/globalphy/phy/phy/plot/_vispy_utils.py", line 137, in _bake
    getattr(self, name)()
  File "/home/skadir/globalphy/phy/phy/plot/waveforms.py", line 198, in _bake_spikes
    data = np.c_[waveforms.ravel(), masks.ravel()].astype(np.float32)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/numpy/lib/index_tricks.py", line 338, in __getitem__
    res = _nx.concatenate(tuple(objs), axis=self.axis)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
WARNING:vispy:Traceback (most recent call last):
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/IPython/kernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/IPython/kernel/zmq/kernelapp.py", line 373, in start
    ioloop.IOLoop.instance().start()
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/tornado/ioloop.py", line 810, in start
    self._run_callback(callback)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/IPython/kernel/zmq/kernelbase.py", line 234, in enter_eventloop
    self.eventloop(self)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/IPython/kernel/zmq/eventloops.py", line 80, in loop_qt4
    start_event_loop_qt4(kernel.app)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/IPython/lib/guisupport.py", line 135, in start_event_loop_qt4
    app.exec_()
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/vispy/app/backends/_qt.py", line 631, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/vispy/util/event.py", line 436, in __call__
    self._invoke_callback(cb, event)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/vispy/util/event.py", line 452, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/vispy/util/event.py", line 448, in _invoke_callback
    cb(event)
  File "/home/skadir/globalphy/phy/phy/plot/waveforms.py", line 484, in on_draw
    self.visual.draw()
  File "/home/skadir/globalphy/phy/phy/plot/_vispy_utils.py", line 144, in draw
    self._bake()
  File "/home/skadir/globalphy/phy/phy/plot/_vispy_utils.py", line 137, in _bake
    getattr(self, name)()
  File "/home/skadir/globalphy/phy/phy/plot/waveforms.py", line 198, in _bake_spikes
    data = np.c_[waveforms.ravel(), masks.ravel()].astype(np.float32)
  File "/home/skadir/miniconda/envs/phyagain/lib/python3.4/site-packages/numpy/lib/index_tricks.py", line 338, in __getitem__
    res = _nx.concatenate(tuple(objs), axis=self.axis)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
ERROR: Invoking <bound method WaveformView.on_draw of <WaveformView (PyQt4) at 0x7f0b040bd630>> for DrawEvent
ERROR:vispy:Invoking <bound method WaveformView.on_draw of <WaveformView (PyQt4) at 0x7f0b040bd630>> for DrawEvent
ERROR: Invoking <bound method WaveformView.on_draw of <WaveformView (PyQt4) at 0x7f0b040bd630>> repeat 2
ERROR:vispy:Invoking <bound method WaveformView.on_draw of <WaveformView (PyQt4) at 0x7f0b040bd630>> repeat 2
ERROR: Invoking <bound method WaveformView.on_draw of <WaveformView (PyQt4) at 0x7f0b040bd630>> repeat 3
ERROR:vispy:Invoking <bound method WaveformView.on_draw of <WaveformView (PyQt4) at 0x7f0b040bd630>> repeat 3
ERROR: Invoking <bound method WaveformView.on_draw of <WaveformView (PyQt4) at 0x7f0b040bd630>> repeat 4
ERROR:vispy:Invoking <bound method WaveformView.on_draw of <WaveformView (PyQt4) at 0x7f0b040bd630>> repeat 4
ERROR: Invoking <bound method WaveformView.on_draw of <WaveformView (PyQt4) at 0x7f0b040bd630>> repeat 5
ERROR:vispy:Invoking <bound method WaveformView.on_draw of <WaveformView (PyQt4) at 0x7f0b040bd630>> repeat 5




```

**Comment by rossant** [comment]
can you reproduce this in the latest version?
