### ISSUE TITLE
valid clusterings are not loaded

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy#652]
I have a file with multiple clusterings, but when I call from the command line like this:

```
phy cluster-manual myFile.kwik --clustering='myClustering'
```

it says the clustering is not valid (see below for error). However, when I open the same file and clustering from an ipython notebook, like this:

```
session = Session(kwik_path, clustering = 'clust_clump_50')
```

it works fine. 

```
[phy] N:\M140528NS1>phy cluster-manual -i 20141202_allGT_child_640001.kwik --clu
stering='clust_clump_50'
Traceback (most recent call last):
  File "C:\Anaconda\envs\phy\Scripts\phy-script.py", line 9, in <module>
    load_entry_point('phy==0.2.0.dev0', 'console_scripts', 'phy')()
  File "c:\users\nick\documents\github\phy\phy\scripts\phy_script.py", line 434,
 in main
    out = func(args)
  File "c:\users\nick\documents\github\phy\phy\scripts\phy_script.py", line 375,
 in cluster_manual
    use_store=not(args.no_store),
  File "c:\users\nick\documents\github\phy\phy\scripts\phy_script.py", line 248,
 in _create_session
    session = Session(kwik_path, **kwargs)
  File "c:\users\nick\documents\github\phy\phy\session\session.py", line 91, in
__init__
    gui_classes=self._gui_classes,
  File "c:\users\nick\documents\github\phy\phy\io\base.py", line 387, in __init_
_
    self.open(path, model=model)
  File "c:\users\nick\documents\github\phy\phy\session\session.py", line 136, in
 open
    return super(Session, self).open(model=model, path=kwik_path)
  File "c:\users\nick\documents\github\phy\phy\io\base.py", line 436, in open
    model = self._create_model(path)
  File "c:\users\nick\documents\github\phy\phy\session\session.py", line 108, in
 _create_model
    waveform_filter=self._waveform_filter,
  File "c:\users\nick\documents\github\phy\phy\io\kwik\model.py", line 333, in _
_init__
    clustering=clustering)
  File "c:\users\nick\documents\github\phy\phy\io\kwik\model.py", line 729, in o
pen
    self._clustering_changed(self._clustering)
  File "c:\users\nick\documents\github\phy\phy\io\kwik\model.py", line 798, in _
clustering_changed
    raise ValueError("The clustering {0} is invalid.".format(value))
ValueError: The clustering 'clust_clump_50' is invalid.
```

**Comment by nippoo** [comment]
Maybe the GUI script is performing some checks that aren't being done by the function itself. This will all change in 0.3.0 but I'll leave it open until then.
