### ISSUE TITLE
Value Error when re-clustering

### ISSUE THREAD

**Issue by tymoreau** [kwikteam/phy#659]
After successfully running `phy spikesort` on a dataset, I ran `phy cluster-auto` to redo the automatic clustering. 

Klustakwik ran but gave an error at the very end:

```
14:06:17 [I] The automatic clustering process has finished.
14:06:17 [I] Switched to `empty` clustering.
Initializing features and masks: 100.0%.
Features and masks initialized.
Initializing features and masks: 100.0%.
Initializing waveforms: 100.0%.
Waveforms initialized.
Initializing statistics: 100.0%.
Statistics initialized.
Initializing statistics: 100.0%.
Traceback (most recent call last):
  File "/home/david/anaconda/bin/phy", line 11, in <module>
    sys.exit(main())
  File "/home/david/anaconda/lib/python3.4/site-packages/phy/scripts/phy_script.py", line 459, in main
    exec_(cmd, {}, ns)
  File "<string>", line 1, in <module>
  File "/home/david/anaconda/lib/python3.4/site-packages/phy/session/session.py", line 440, in cluster
    self.model.copy_clustering('main', 'original')
  File "/home/david/anaconda/lib/python3.4/site-packages/phy/io/kwik/model.py", line 915, in copy_clustering
    self._move_clustering(name, new_name, copy=True)
  File "/home/david/anaconda/lib/python3.4/site-packages/phy/io/kwik/model.py", line 882, in _move_clustering
    "already exists.")
ValueError: The clustering 'original' already exists.
```

**Comment by rossant** [comment]
should be fixed in *klusta*
