### ISSUE TITLE
KwikCreator doesn't work with n_features != 3

### ISSUE THREAD

**Issue by nippoo** [kwikteam/phy#665]
```
Traceback (most recent call last):
  File "/Users/nippoo/miniconda/envs/phy/bin/phy", line 9, in <module>
    load_entry_point('phy==0.2.2', 'console_scripts', 'phy')()
  File "/Users/nippoo/Development/phy/phy/scripts/phy_script.py", line 459, in main
    exec_(cmd, {}, ns)
  File "<string>", line 1, in <module>
  File "/Users/nippoo/Development/phy/phy/session/session.py", line 341, in detect
    n_features=n_features,
  File "/Users/nippoo/Development/phy/phy/io/kwik/creator.py", line 232, in add_spikes
    _write_by_chunk(fm, fm_arrs)
  File "/Users/nippoo/Development/phy/phy/io/kwik/creator.py", line 37, in _write_by_chunk
    for arr in arrs:
  File "/Users/nippoo/Development/phy/phy/io/kwik/creator.py", line 231, in <genexpr>
    if fet is not None and m is not None)
  File "/Users/nippoo/miniconda/envs/phy/lib/python3.4/site-packages/numpy/lib/shape_base.py", line 367, in dstack
    return _nx.concatenate([atleast_3d(_m) for _m in tup], 2)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```

**Comment by rossant** [comment]
fixed
