### ISSUE TITLE
save cluster groups error

### ISSUE THREAD

**Issue by danieljdenman** [kwikteam/phy#679]
i just pulled the most recent versions of phy and on the killkwik branch, and phycontrib; now i'm getting the following when i try to save my clustering:

> Traceback (most recent call last):
  File "/Users/administrator/anaconda/lib/python2.7/site-packages/phy/phy/gui/actions.py", line 122, in wrapped
    return callback(*args, **kwargs)
  File "/Users/administrator/anaconda/lib/python2.7/site-packages/phy/phy/cluster/manual/gui_component.py", line 563, in save
    self.gui.emit('request_save', spike_clusters, groups)
  File "/Users/administrator/anaconda/lib/python2.7/site-packages/phy/phy/gui/gui.py", line 216, in emit
    return self._event.emit(*args, **kwargs)
  File "/Users/administrator/anaconda/lib/python2.7/site-packages/phy/phy/utils/event.py", line 121, in emit
    res.append(callback(*args, **kwargs))
  File "/Users/administrator/anaconda/lib/python2.7/site-packages/phy-contrib/phycontrib/template/gui.py", line 507, in on_request_save
    with open(filenames['cluster_groups'], 'w', newline='') as f:
TypeError: 'newline' is an invalid keyword argument for this function

removing ", newline = '' "  lets me save, but i'm not sure what it is supposed to do or if that messes something up.

**Comment by rossant** [comment]
this has been fixed -- it was a Python 2 bug
