### ISSUE TITLE
Traceview questions

### ISSUE THREAD

**Issue by juplab** [kwikteam/phy#804]
Hi,

Thanks for all your contributions, I am new to spike sorting and very excited to be able to use the tools you developed to address our biological questions.
As I am trying to set up phy I encountered an issue with display of Traceview on Windows 7 and Mac 10.13.6 using the small test dataset provided here https://phy-contrib.readthedocs.io/en/latest/template-gui/#test-datasets (see below). 

The display I obtain is very different from what is posted on gitHub any input would be greatly appreciated.
Thanks

![phy-traceview](https://user-images.githubusercontent.com/34900992/45652507-d2dd8000-baa2-11e8-9d9c-63d687ff13cd.png)

and on mac I obtain the following error

RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_FRAMEBUFFER_OPERATION
17:30:49 [W] logs:271             Traceback (most recent call last):
  File "/Users/lab/miniconda3/envs/phy/bin/phy", line 11, in <module>
    sys.exit(phy())
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/phycontrib/template/gui.py", line 814, in cluster_manual
    _run_cmd('_run(params)', ctx, globals(), locals())
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/phy/utils/cli.py", line 76, in _run_cmd
    return exec_(cmd, glob, loc)
  File "<string>", line 1, in <module>
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/phycontrib/template/gui.py", line 789, in _run
    run_app()
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/phy/gui/qt.py", line 106, in wrapped
    return func(*args, **kwargs)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/phy/gui/qt.py", line 127, in run_app
    return QT_APP.exit(QT_APP.exec_())
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/vispy/app/backends/_qt.py", line 436, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/vispy/app/backends/_qt.py", line 708, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/phy/plot/base.py", line 300, in on_draw
    visual.on_draw()
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/phy/plot/base.py", line 73, in on_draw
    self.program.draw(self.gl_primitive_type)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/vispy/gloo/program.py", line 470, in draw
    canvas.context.flush_commands()
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/vispy/gloo/context.py", line 171, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/vispy/gloo/glir.py", line 232, in flush
    self._shared.flush(parser)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/vispy/gloo/glir.py", line 146, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/vispy/gloo/glir.py", line 477, in parse
    self._parse(command)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/vispy/gloo/glir.py", line 439, in _parse
    ob.draw(*args)
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/vispy/gloo/glir.py", line 918, in draw
    gl.check_error('Check before draw')
  File "/Users/lab/miniconda3/envs/phy/lib/python3.5/site-packages/vispy/gloo/gl/__init__.py", line 211, in check_error
    raise err
RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_FRAMEBUFFER_OPERATION
ERROR: Invoking <bound method BaseCanvas.on_draw of <AmplitudeView (PyQt4) at 0x1c2948d748>> for DrawEvent
17:30:49 [E] logs:325             Invoking <bound method BaseCanvas.on_draw of <AmplitudeView (PyQt4) at 0x1c2948d748>> for DrawEvent

**Comment by juplab** [comment]
solved in previous post
